services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    env_file: ${DATA_DIR}/variables/.env
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    env_file: ${DATA_DIR}/variables/.env
    networks:
      - inception
    restart: unless-stopped



volumes:
  wordpress:
    driver: local # this is the default, but we just make it explicit, could also be a temporary thing in RAM for example
    driver_opts: # gives extra options to the volume
      type: none # we set it so docker doesnt try to automatically infer what type it is, could be the RAM thing or a network based volume otherwise
      device: ${DATA_DIR}/web # the directory that you want to bind to the volume
      o: bind # will bind the ./web folder to the folde ron the container, without it will create a folder in some docker directory

  database:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIR}/database
      o: bind



networks:
  inception:
    driver: "bridge"
